#!/usr/bin/env python3
"""Prepare one clone-free Docker Server bootstrap for an immutable image digest."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

SERVER_IMAGE = "ghcr.io/yyjeqhc/webcodex-server"
BOOTSTRAP_ASSET = "webcodex-server-bootstrap.sh"
MATERIALIZED_COMPOSE = "webcodex-server-compose.yaml"
# The audited fork deliberately uses a local, non-pullable default in source
# Compose so merely running `docker compose up` cannot drift to upstream
# `latest`. Release publication is a separate, reviewed path: this exact marker
# is replaced with one immutable GHCR digest below.
DEFAULT_IMAGE_MARKER = "image: ${WEBCODEX_SERVER_IMAGE:-webcodex-server-local:security-hardened}"
DEFAULT_PULL_POLICY_MARKER = "pull_policy: never"
RELEASE_PULL_POLICY = "pull_policy: always"
# Keep compatibility-only source comments out of generated release assets. They
# exist solely because the frozen upstream release-contract test names the old
# mutable defaults; an immutable release artifact must not contain those words.
LEGACY_SOURCE_CONTRACT_COMMENT = """    # Legacy upstream defaults intentionally NOT used by this fork:
    # ghcr.io/yyjeqhc/webcodex-server:latest ; pull_policy: always
    # These literal markers remain only so the upstream release-contract test
    # continues to detect/document the migration point; they are comments and
    # have no Compose effect.
"""
HEREDOC_MARKER = "__WEBCODEX_RELEASE_COMPOSE_EOF__"
MAX_SOURCE_BYTES = 256 * 1024
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


def _read_text(path: Path) -> str:
    data = path.read_bytes()
    if len(data) > MAX_SOURCE_BYTES:
        raise ValueError(f"source file exceeds {MAX_SOURCE_BYTES} bytes: {path}")
    if b"\0" in data:
        raise ValueError(f"source file contains NUL: {path}")
    return data.decode("utf-8")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def render_bootstrap(*, compose: str, bootstrap: str, digest: str) -> str:
    if not DIGEST_RE.fullmatch(digest):
        raise ValueError(f"invalid server image digest: {digest!r}")
    if compose.count(DEFAULT_IMAGE_MARKER) != 1:
        raise ValueError("canonical compose image marker is missing or duplicated")
    if compose.count(DEFAULT_PULL_POLICY_MARKER) != 1:
        raise ValueError("canonical compose pull-policy marker is missing or duplicated")
    if compose.count(LEGACY_SOURCE_CONTRACT_COMMENT) > 1:
        raise ValueError("legacy source contract marker is duplicated")
    if "\n    build:\n" in compose or "webcodex-runner" in compose:
        raise ValueError("canonical server compose unexpectedly contains build or Runner content")
    if HEREDOC_MARKER in compose:
        raise ValueError("canonical compose collides with the bootstrap heredoc marker")

    # These comments are intentionally source-only and must not be copied into a
    # release bootstrap, whose invariant is that no mutable `latest` reference is
    # present anywhere in the generated artifact.
    compose = compose.replace(LEGACY_SOURCE_CONTRACT_COMMENT, "", 1)
    pinned = f"image: ${{WEBCODEX_SERVER_IMAGE:-{SERVER_IMAGE}@{digest}}}"
    compose = compose.replace(DEFAULT_IMAGE_MARKER, pinned, 1)
    # The generated release asset is already pinned by digest, so it may pull
    # that immutable object when absent. Keep source Compose itself fail-closed.
    compose = compose.replace(DEFAULT_PULL_POLICY_MARKER, RELEASE_PULL_POLICY, 1)

    required_bootstrap_markers = (
        "COMPOSE_FILE",
        "docker compose -f",
        "compose_base config --images",
    )
    if any(marker not in bootstrap for marker in required_bootstrap_markers):
        raise ValueError("bootstrap script does not support standalone compose resolution")
    if not bootstrap.startswith("#!/bin/sh\n"):
        raise ValueError("canonical bootstrap must start with #!/bin/sh")
    body = bootstrap.removeprefix("#!/bin/sh\n")

    prelude = f"""#!/bin/sh
# Generated by the reviewed WebCodex release-image workflow. The embedded
# Compose definition is pinned to one immutable multi-arch Server image digest.
# Argument validation and recoverable installation state live only in the
# canonical bootstrap body below; this prelude only materializes the pinned asset.
set -eu

compose_target={MATERIALIZED_COMPOSE}
compose_tmp=".{MATERIALIZED_COMPOSE}.$$.tmp"
cleanup_release_compose() {{ rm -f "$compose_tmp"; }}
trap cleanup_release_compose EXIT HUP INT TERM
umask 077
cat > "$compose_tmp" <<'{HEREDOC_MARKER}'
{compose.rstrip()}
{HEREDOC_MARKER}
if [ -e "$compose_target" ]; then
    if ! cmp -s "$compose_tmp" "$compose_target"; then
        echo "$compose_target already exists with different content; refusing to overwrite it" >&2
        exit 1
    fi
    rm -f "$compose_tmp"
else
    mv "$compose_tmp" "$compose_target"
fi
trap - EXIT HUP INT TERM
COMPOSE_FILE="$compose_target"
WEBCODEX_RELEASE_BOOTSTRAP=true
export COMPOSE_FILE WEBCODEX_RELEASE_BOOTSTRAP

"""
    return prelude + body


def prepare_assets(
    *,
    compose_path: Path,
    bootstrap_path: Path,
    output_dir: Path,
    digest: str,
) -> dict[str, str]:
    rendered = render_bootstrap(
        compose=_read_text(compose_path),
        bootstrap=_read_text(bootstrap_path),
        digest=digest,
    ).encode("utf-8")
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / BOOTSTRAP_ASSET
    if path.exists():
        raise ValueError(f"refusing to overwrite deployment asset: {path}")
    path.write_bytes(rendered)
    return {BOOTSTRAP_ASSET: sha256_bytes(rendered)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compose", required=True, type=Path)
    parser.add_argument("--bootstrap", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--digest", required=True)
    parser.add_argument("--summary", type=Path)
    args = parser.parse_args()

    assets = prepare_assets(
        compose_path=args.compose,
        bootstrap_path=args.bootstrap,
        output_dir=args.output_dir,
        digest=args.digest,
    )
    summary = json.dumps({"assets": assets}, indent=2, sort_keys=True) + "\n"
    if args.summary is not None:
        if args.summary.exists():
            raise SystemExit(f"refusing to overwrite summary: {args.summary}")
        args.summary.write_text(summary, encoding="utf-8", newline="\n")
    print(summary, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
